// ============================================
// DATOS VERIFICADOS - SISMO COLOMBIA 10 AGOSTO 2026
// Fuentes: SGC, USGS, UNGRD, Cruz Roja Colombiana, Medios Oficiales & Reportes Comunitarios
// ============================================

const DATA_KEY = 'earthquake_data_v2026_colombia_v8';

const initialData = {
    epicenter: {
        name: "San José del Palmar, Chocó",
        lat: 5.3833,
        lng: -76.2333,
        magnitude: 7.4,
        time: "07:34 AM (hora local)",
        depth: "107 km",
        date: "10 de Agosto de 2026",
        source: "Servicio Geológico Colombiano (SGC) / USGS"
    },

    affectedZones: [
        { id: 'zone1', name: 'Pereira', department: 'Risaralda', lat: 4.8133, lng: -75.6961, severity: 'critical', radius: 22000, details: 'Reportes de víctimas mortales y heridos. Afectaciones en edificaciones y suspensión preventiva de operaciones en Aeropuerto Matecaña.' },
        { id: 'zone2', name: 'Manizales', department: 'Caldas', lat: 5.0689, lng: -75.5174, severity: 'severe', radius: 18000, details: 'Fallecidos confirmados por autoridades locales. Daños en estructura de la Catedral Basílica y suspensión en Aeropuerto La Nubia.' },
        { id: 'zone3', name: 'Armenia', department: 'Quindío', lat: 4.5339, lng: -75.6811, severity: 'severe', radius: 16000, details: 'Daños estructurales en edificaciones. Operaciones en Aeropuerto El Edén suspendidas por revisión técnica.' },
        { id: 'zone4', name: 'Cali', department: 'Valle del Cauca', lat: 3.4516, lng: -76.5320, severity: 'critical', radius: 28000, details: 'Más de 20 estructuras colapsadas reportadas. Puestos de respuesta activados por la Alcaldía y solicitud de apoyo nacional.' },
        { id: 'zone5', name: 'Quibdó', department: 'Chocó', lat: 5.6944, lng: -76.6583, severity: 'critical', radius: 24000, details: 'Cercano al epicentro. Gobernación reporta heridos y daños estructurales. Aeropuerto El Caraño suspendido.' },
        { id: 'zone6', name: 'Cartago', department: 'Valle del Cauca', lat: 4.7461, lng: -75.9119, severity: 'moderate', radius: 12000, details: 'Operaciones suspendidas en Aeropuerto Santa Ana. Evaluaciones de seguridad por Gestión del Riesgo.' },
        { id: 'zone7', name: 'Buenaventura', department: 'Valle del Cauca', lat: 3.8801, lng: -77.0311, severity: 'moderate', radius: 15000, details: 'Suspensión preventiva de vuelos en Aeropuerto Gerardo Tobar López. Inspecciones en zona portuaria.' },
        { id: 'zone8', name: 'San José del Palmar', department: 'Chocó', lat: 5.3833, lng: -76.2333, severity: 'critical', radius: 35000, details: 'EPICENTRO DEL SISMO (Mag. 7.4). Zona rural con despliegue prioritario de equipos de rescate.' }
    ],

    // CENTROS DE ACOPIO VERIFICADOS Y REGISTRADOS
    collectionCenters: [
        {
            id: 'acop_cali_luzmery',
            name: 'Centro Deportivo Luz Mery Tristán',
            address: 'Autopista Cali-Jamundí # 120-00, Cali, Valle del Cauca',
            city: 'Cali',
            lat: 3.3556,
            lng: -76.5385,
            type: 'collection',
            contactName: 'Luz Elena Restrepo (Gestión Social)',
            contact: '315 489 2011',
            needs: 'Agua potable, víveres, guantes de carnaza, seguetas, alcohol y mantas de abrigo.',
            schedule: '8:00 AM - 8:00 PM',
            verified: true,
            dateAdded: '10/08/2026, 08:30:00'
        },
        {
            id: 'acop_cali_jairo_varela',
            name: 'Plazoleta Jairo Varela',
            address: 'Av. 2 Nte. # 10-01, Granada, Cali, Valle del Cauca',
            city: 'Cali',
            lat: 3.4542,
            lng: -76.5348,
            type: 'collection',
            contactName: 'Andrés Felipe Caicedo (Puesto de Mando Unificado)',
            contact: '310 523 9811',
            needs: 'Guantes de construcción, cascos de protección, agua potable, colchonetas y gafas de seguridad.',
            schedule: 'Abierto 24 Horas',
            verified: true,
            dateAdded: '10/08/2026, 09:15:00'
        },
        {
            id: 'acop_cali_banco',
            name: 'Banco de Alimentos de Cali',
            address: 'Calle 24 # 6-103, Cali, Valle del Cauca',
            city: 'Cali',
            lat: 3.4560,
            lng: -76.5230,
            type: 'collection',
            contactName: 'Banco de Alimentos Cali',
            contact: '(602) 889 1234',
            needs: 'Alimentos no perecederos, agua embotellada, medicinas, kits de aseo personal y elementos para bebés.',
            schedule: '8:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_medellin_eafit',
            name: 'Universidad EAFIT - Bloque 29, Piso 5',
            address: 'Cra 49 # 7 Sur-50, El Poblado, Medellín, Antioquia',
            city: 'Medellín',
            lat: 6.2007,
            lng: -75.5784,
            type: 'collection',
            contactName: 'Voluntariado @CAS_OE',
            contact: '+57 322 849 1960',
            needs: 'Medicamentos, alimentos no perecederos, agua potable, ropa en buen estado y elementos de primeros auxilios.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '10/08/2026, 09:40:00'
        },
        {
            id: 'acop_medellin_banco',
            name: 'Fundación Arquidiocesana Banco de Alimentos de Medellín',
            address: 'Carrera 52 # 30A-97, Barrio Guayabal, Medellín, Antioquia',
            city: 'Medellín',
            lat: 6.2285,
            lng: -75.5780,
            type: 'collection',
            contactName: 'Banco de Alimentos de Medellín',
            contact: '(604) 341 4141',
            needs: 'Alimentos no perecederos, agua potable, medicinas, kits de aseo personal, ropa en buen estado y elementos para bebés.',
            schedule: '8:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_medellin_saciar',
            name: 'Fundación Saciar - Barrio Belén',
            address: 'Carrera 50 # 25-261, Barrio Belén, Medellín, Antioquia',
            city: 'Medellín',
            lat: 6.2270,
            lng: -75.5840,
            type: 'collection',
            contactName: 'Fundación Saciar',
            contact: '(604) 444 7171',
            needs: 'Alimentos no perecederos, agua potable, elementos de higiene, cobijas y ropa en buen estado.',
            schedule: '8:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_samusur',
            name: 'Samu Sur - Centro de Acopio',
            address: 'Avenida Carrera 68 # 31-41 sur, Bogotá',
            city: 'Bogotá',
            lat: 4.5950,
            lng: -74.1350,
            type: 'collection',
            contactName: 'Secretaría de Salud / Red Samu Sur',
            contact: 'Línea 123 / Samu Sur',
            needs: 'Alimentos no perecederos, agua potable, medicinas, kits de aseo personal, ropa en buen estado y elementos para bebés.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_samunorte',
            name: 'Samu Norte - Centro de Acopio',
            address: 'Calle 134 - Carrera 7B Bis # 132-31, Bogotá',
            city: 'Bogotá',
            lat: 4.7088,
            lng: -74.0305,
            type: 'collection',
            contactName: 'Secretaría de Salud / Red Samu Norte',
            contact: 'Línea 123 / Samu Norte',
            needs: 'Alimentos no perecederos, agua potable, medicinas, kits de aseo personal, ropa en buen estado y elementos para bebés.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_salvamento',
            name: 'Centro de Salvamento Acuático',
            address: 'Avenida La Esmeralda # 63-81, Bogotá',
            city: 'Bogotá',
            lat: 4.6595,
            lng: -74.0880,
            type: 'collection',
            contactName: 'Defensa Civil / Salvamento Acuático',
            contact: 'Línea 144 / Red Bogotá',
            needs: 'Alimentos no perecederos, agua, medicinas, kits de aseo personal, ropa en buen estado y elementos para bebés.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_cruzroja_admin',
            name: 'Cruz Roja Colombiana - Sede Administrativa',
            address: 'Carrera 24 # 73-38, Bogotá',
            city: 'Bogotá',
            lat: 4.6635,
            lng: -74.0675,
            type: 'collection',
            contactName: 'Cruz Roja Colombiana Cundinamarca/Bogotá',
            contact: '(601) 4376300',
            needs: 'Alimentos no perecederos, agua potable, medicamentos, kits de aseo personal, ropa en buen estado y elementos para bebés.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_cruzroja_bodega',
            name: 'Bodega Cruz Roja Colombiana',
            address: 'Diagonal 79B # 62-53, Bogotá',
            city: 'Bogotá',
            lat: 4.6780,
            lng: -74.0820,
            type: 'collection',
            contactName: 'Logística Cruz Roja Colombiana',
            contact: '(601) 4376300',
            needs: 'Alimentos no perecederos, agua embotellada, medicamentos, kits de higiene y cobijas.',
            schedule: '8:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_palacio_deportes',
            name: 'Palacio de los Deportes',
            address: 'Calle 63 # 59A-06, Bogotá',
            city: 'Bogotá',
            lat: 4.6575,
            lng: -74.0865,
            type: 'collection',
            contactName: 'IDRD / Gestión del Riesgo Bogotá',
            contact: 'Línea 123',
            needs: 'Alimentos no perecederos, agua potable, frazadas, insumos médicos y elementos para bebés.',
            schedule: '7:00 AM - 7:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_jardin_origen',
            name: 'Casa Jardín Origen (Ayuda para Chocó)',
            address: 'Calle 38 # 29-29, Barrio Teusaquillo, Bogotá',
            city: 'Bogotá',
            lat: 4.6290,
            lng: -74.0805,
            type: 'collection',
            contactName: 'Colectivo Jardín Origen (@jackemaldonado_)',
            contact: 'Instagram @jackemaldonado_',
            needs: 'Agua potable, alimentos no perecederos, elementos de aseo personal, cobijas y medicinas destinadas al Chocó.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_human_construction',
            name: 'Human Construction (Ayuda para Chocó)',
            address: 'Carrera 52A # 134D-23 Local 1, Bogotá',
            city: 'Bogotá',
            lat: 4.7215,
            lng: -74.0550,
            type: 'collection',
            contactName: 'Human Construction',
            contact: 'Local 1 - Recepción de Acopio',
            needs: 'Agua, alimentos no perecederos, elementos de aseo, cobijas y medicinas destinadas al Chocó.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_catalina_munoz',
            name: 'Fundación Catalina Muñoz (Ayuda para Chocó)',
            address: 'Diagonal 48 # 19-16, Bogotá',
            city: 'Bogotá',
            lat: 4.6360,
            lng: -74.0710,
            type: 'collection',
            contactName: 'Fundación Catalina Muñoz',
            contact: 'Sede Teusaquillo',
            needs: 'Agua, alimentos no perecederos, elementos de aseo, cobijas y medicinas destinadas al Chocó.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_barranquilla_sec',
            name: 'Centro de Acopio Sector Barranquillita',
            address: 'Carrera 43 # 6-120, Sector Barranquillita, Barranquilla, Atlántico',
            city: 'Barranquilla',
            lat: 10.9785,
            lng: -74.7758,
            type: 'collection',
            contactName: 'Defensa Civil Distrital Barranquilla',
            contact: '300 654 1120',
            needs: 'Alimentos no perecederos, agua potable, elementos de aseo personal y colchonetas.',
            schedule: 'Abierto 24 horas (según disposición distrital)',
            verified: true,
            dateAdded: '10/08/2026, 10:10:00'
        },
        {
            id: 'acop_armenia_banco',
            name: 'Banco de Alimentos Monseñor Roberto López Londoño',
            address: 'Cra. 19 # 50-00, Armenia, Quindío',
            city: 'Armenia',
            lat: 4.5268,
            lng: -75.6892,
            type: 'collection',
            contactName: 'Padre José Manuel Ortiz',
            contact: '312 876 5432',
            needs: 'Granos, enlatados, agua embotellada, cobijas y kits de primeros auxilios.',
            schedule: '7:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '10/08/2026, 10:45:00'
        },
        {
            id: 'acop_manizales_banco',
            name: 'Banco de Alimentos de Manizales',
            address: 'Calle 24 # 22-02, Centro, Manizales, Caldas',
            city: 'Manizales',
            lat: 5.0678,
            lng: -75.5189,
            type: 'collection',
            contactName: 'Gladys Ramírez (Coordinación de Acopio)',
            contact: '311 345 6789',
            needs: 'Agua embotellada, frazadas, leche en polvo, pañales y medicamentos básicos.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '10/08/2026, 11:20:00'
        },
        {
            id: 'acop_doral_gem',
            name: 'Global Empowerment Mission (GEM) - Drop-Off Doral',
            address: '1850 NW 84th Ave #100, Doral, FL 33126, EE.UU.',
            city: 'Doral (Florida, EE.UU.)',
            lat: 25.7925,
            lng: -80.3328,
            type: 'collection',
            contactName: 'Global Empowerment Mission (GEM) Team',
            contact: 'info@gem.org / gem.org/volunteer',
            needs: 'Refugio (carpas, sleeping bags, catres, colchones, cobijas, guantes/botas trabajo, mascarillas KN95, linternas solares, power banks, radios, botiquines), Higiene (crema/cepillos, desodorante, higiene femenina, pañales adultos), Bebés (pañales, teteros, pañitos, ropa nueva).',
            schedule: '9:00 AM - 5:00 PM (Lunes a Domingo)',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'acop_bogota_usaquen',
            name: 'Punto Acopio Usaquén (Global Shapers)',
            address: 'AC 116 # 11C-22, Usaquén, Bogotá',
            city: 'Bogotá',
            lat: 4.6980,
            lng: -74.0375,
            type: 'collection',
            contactName: 'Global Shapers Community / @jackemaldonado_',
            contact: 'Recepción 24 horas',
            needs: 'Alimentos no perecederos, medicamentos, bebidas y productos de higiene personal. (Priorizado: NO ropa).',
            schedule: 'Disponible las 24 horas',
            verified: true,
            dateAdded: '11/08/2026, 12:44:00'
        },
        {
            id: 'acop_bogota_puente_aranda',
            name: 'Punto Acopio Puente Aranda',
            address: 'TV 52C # 2-46, Puente Aranda, Bogotá',
            city: 'Bogotá',
            lat: 4.6185,
            lng: -74.1160,
            type: 'collection',
            contactName: 'Global Shapers Community / @jackemaldonado_',
            contact: 'Punto de Acopio',
            needs: 'Alimentos no perecederos, medicamentos, bebidas y productos de higiene personal. (Priorizado: NO ropa).',
            schedule: '8:00 AM - 9:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:44:00'
        },
        {
            id: 'acop_bogota_multiplaza',
            name: 'Punto Acopio C.C. Multiplaza (Sótano 2)',
            address: 'Calle 19A # 72-57, Sótano 2 (Entrada del Éxito), Bogotá',
            city: 'Bogotá',
            lat: 4.6520,
            lng: -74.1265,
            type: 'collection',
            contactName: 'Global Shapers / C.C. Multiplaza',
            contact: 'Sótano 2 (Entrada del Éxito)',
            needs: 'Alimentos no perecederos, medicamentos, bebidas y productos de higiene personal. (Priorizado: NO ropa).',
            schedule: '2:00 PM - 9:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:44:00'
        },
        {
            id: 'acop_manizales_banco_arquidiocesano',
            name: 'Banco Arquidiócesano de Alimentos de Manizales',
            address: 'Calle 49 # 27A-85, Manizales, Caldas',
            city: 'Manizales',
            lat: 5.0560,
            lng: -75.4950,
            type: 'collection',
            contactName: 'Arquidiócesis de Manizales',
            contact: 'Recepción de Donaciones Manizales',
            needs: 'Alimentos no perecederos, agua embotellada, frazadas, leche en polvo, pañales y medicamentos.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:44:00'
        },
        {
            id: 'acop_bogota_tadeo',
            name: 'Universidad Jorge Tadeo Lozano - Centro Acopio Oficial',
            address: 'Carrera 4 # 22-61, La Candelaria, Bogotá',
            city: 'Bogotá',
            lat: 4.6045,
            lng: -74.0680,
            type: 'collection',
            contactName: 'Voluntariado Utadeo / Cruz Roja',
            contact: '(601) 242 7030',
            needs: 'Agua embotellada, cobijas, kits de higiene personal y linternas.',
            schedule: '8:00 AM - 7:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 14:00:00'
        },
        {
            id: 'acop_bogota_unicentro',
            name: 'C.C. Unicentro - Punto Acopio Cruz Roja',
            address: 'Carrera 15 # 124-30, Usaquén, Bogotá',
            city: 'Bogotá',
            lat: 4.7015,
            lng: -74.0335,
            type: 'collection',
            contactName: 'Punto Institucional Cruz Roja',
            contact: 'Línea 132',
            needs: 'Alimentos no perecederos, pañales y suministros médicos básicos.',
            schedule: '9:00 AM - 8:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 14:15:00'
        },
        {
            id: 'acop_quibdo_terpel_cabi',
            name: 'Estación Terpel Cabí - Acopio Emergencia Chocó',
            address: 'Av. Aeropuerto Sector Cabí, Quibdó, Chocó',
            city: 'Quibdó',
            lat: 5.6880,
            lng: -76.6510,
            type: 'collection',
            contactName: 'Alcaldía de Quibdó / Asocapitales',
            contact: '315 765 1122',
            needs: 'Agua potable urgente, mosquiteros, alimentos enlatados y suero oral.',
            schedule: 'Abierto 24 Horas',
            verified: true,
            dateAdded: '11/08/2026, 14:30:00'
        },
        {
            id: 'acop_cali_licorera',
            name: 'Antigua Licorera del Valle - Acopio Departamental',
            address: 'Carrera 1 # 26-85, Cali, Valle del Cauca',
            city: 'Cali',
            lat: 3.4680,
            lng: -76.5180,
            type: 'collection',
            contactName: 'Gobernación del Valle del Cauca',
            contact: '(602) 620 0000',
            needs: 'Herramientas de rescate, cascos, agua, alimentos y kits para mascotas.',
            schedule: '8:00 AM - 8:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 15:00:00'
        },
        {
            id: 'acop_bogota_casavalle',
            name: 'Casa del Valle en Bogotá - Acopio Regional',
            address: 'Calle 34 # 5-50, Barrio La Merced, Bogotá',
            city: 'Bogotá',
            lat: 4.6210,
            lng: -74.0685,
            type: 'collection',
            contactName: 'Casa del Valle / Gestión Social',
            contact: '(601) 288 4400',
            needs: 'Ayudas humanitarias priorizadas para despacho a Valle del Cauca y Chocó.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 15:30:00'
        },
        {
            id: 'acop_bucaramanga_cruzroja',
            name: 'Cruz Roja Seccional Santander - Acopio',
            address: 'Calle 45 # 28-10, Bucaramanga, Santander',
            city: 'Bucaramanga',
            lat: 7.1180,
            lng: -73.1190,
            type: 'collection',
            contactName: 'Cruz Roja Seccional Santander',
            contact: '(607) 634 3535',
            needs: 'Frazadas, kits de aseo, alimentos no perecederos y colchonetas.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 16:00:00'
        },
        {
            id: 'acop_pasto_alcaldia',
            name: 'Centro de Acopio Plaza de Nariño',
            address: 'Carrera 25 # 18-50, Pasto, Nariño',
            city: 'Pasto',
            lat: 1.2140,
            lng: -77.2780,
            type: 'collection',
            contactName: 'Gestión del Riesgo Pasto',
            contact: '(602) 729 1919',
            needs: 'Ropa de abrigo, leche en polvo, alimentos y frazadas térmicas.',
            schedule: '8:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 16:30:00'
        },
        {
            id: 'acop_ibague_cruzroja',
            name: 'Cruz Roja Seccional Tolima',
            address: 'Carrera 5 # 39-56, Ibagué, Tolima',
            city: 'Ibagué',
            lat: 4.4390,
            lng: -75.2080,
            type: 'collection',
            contactName: 'Cruz Roja Tolima',
            contact: '(608) 265 8000',
            needs: 'Medicamentos, agua embotellada y elementos de primeros auxilios.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 17:00:00'
        }
    ],

    // REFUGIOS Y ALBERGUES TEMPORALES VERIFICADOS
    shelters: [
        {
            id: 'shelter_manizales_coliseo',
            name: 'Albergue Temporal Coliseo Mayor de Manizales',
            address: 'Av. Lindsay, Sector Universitario, Manizales, Caldas',
            city: 'Manizales',
            lat: 5.0624,
            lng: -75.4965,
            type: 'shelter',
            capacity: 350,
            occupancy: 140,
            contactName: 'Gestión del Riesgo Caldas / Cruz Roja',
            contact: '314 567 8901',
            needs: 'Alojamiento temporal habilitado para familias vulnerables y evacuadas por sismo.',
            verified: true,
            dateAdded: '10/08/2026, 08:00:00'
        },
        {
            id: 'shelter_cali_evangelista',
            name: 'Albergue Temporal Coliseo Evangelista Mora',
            address: 'Calle 5 con Carrera 36, Barrio San Fernando, Cali, Valle del Cauca',
            city: 'Cali',
            lat: 3.4290,
            lng: -76.5410,
            type: 'shelter',
            capacity: 500,
            occupancy: 210,
            contactName: 'Gestión del Riesgo Cali / Cruz Roja Seccional Valle',
            contact: '(602) 514 1100',
            needs: 'Alojamiento para familias evacuadas de estructuras colapsadas. Se requieren colchonetas y cobijas.',
            verified: true,
            dateAdded: '10/08/2026, 10:00:00'
        },
        {
            id: 'shelter_pereira_cuba',
            name: 'Albergue Temporal Coliseo de Cuba',
            address: 'Carrera 25 # 71B-01, Sector Cuba, Pereira, Risaralda',
            city: 'Pereira',
            lat: 4.8020,
            lng: -75.7350,
            type: 'shelter',
            capacity: 300,
            occupancy: 180,
            contactName: 'Defensa Civil Risaralda',
            contact: '312 456 7890',
            needs: 'Espacio de refugio habilitado con atención médica básica e infantil.',
            verified: true,
            dateAdded: '10/08/2026, 11:30:00'
        },
        {
            id: 'shelter_quibdo_polideportivo',
            name: 'Albergue Temporal Polideportivo de Quibdó',
            address: 'Calle 20 # 5-12, Quibdó, Chocó',
            city: 'Quibdó',
            lat: 5.6920,
            lng: -76.6550,
            type: 'shelter',
            capacity: 400,
            occupancy: 310,
            contactName: 'Gobernación del Chocó / Cruz Roja',
            contact: '315 987 6543',
            needs: 'Refugio prioritario zona epicentro. Gran requerimiento de mosquiteros, agua potable y kits de aseo.',
            verified: true,
            dateAdded: '10/08/2026, 09:00:00'
        },
        {
            id: 'shelter_bogota_salitre',
            name: 'Albergue Temporal Coliseo El Salitre',
            address: 'Av. Carrera 68 # 53-07, Bogotá',
            city: 'Bogotá',
            lat: 4.6620,
            lng: -74.0910,
            type: 'shelter',
            capacity: 600,
            occupancy: 120,
            contactName: 'IDIGER / Alcaldía Mayor de Bogotá',
            contact: 'Línea 123 / IDIGER',
            needs: 'Punto receptor para evacuados y soporte a brigadas de auxilio.',
            verified: true,
            dateAdded: '11/08/2026, 09:00:00'
        },
        {
            id: 'shelter_quibdo_colegio',
            name: 'Albergue Colegio Carrasquilla Industrial',
            address: 'Carrera 3 # 24-45, Quibdó, Chocó',
            city: 'Quibdó',
            lat: 5.6940,
            lng: -76.6590,
            type: 'shelter',
            capacity: 450,
            occupancy: 280,
            contactName: 'Defensa Civil / Alcaldía Quibdó',
            contact: '312 876 5432',
            needs: 'Colchonetas, colchas, kit higiénicos y agua limpia.',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'shelter_pereira_expofuturo',
            name: 'Albergue Temporal Expofuturo Pereira',
            address: 'Carrera 19 # 93-02, Villa Olímpica, Pereira, Risaralda',
            city: 'Pereira',
            lat: 4.7950,
            lng: -75.7410,
            type: 'shelter',
            capacity: 500,
            occupancy: 190,
            contactName: 'Gestión del Riesgo Pereira',
            contact: '(606) 324 8000',
            needs: 'Atención humanitaria para damnificados de viviendas destruidas.',
            verified: true,
            dateAdded: '11/08/2026, 12:30:00'
        },
        {
            id: 'shelter_armenia_estadio',
            name: 'Albergue Estadio Centenario de Armenia',
            address: 'Av. Centenario Sector Sur, Armenia, Quindío',
            city: 'Armenia',
            lat: 4.5120,
            lng: -75.6980,
            type: 'shelter',
            capacity: 400,
            occupancy: 165,
            contactName: 'Cruz Roja Quindío',
            contact: '(606) 749 3000',
            needs: 'Kits de aseo, colchonetas y módulos infantiles.',
            verified: true,
            dateAdded: '11/08/2026, 13:00:00'
        },
        {
            id: 'shelter_cali_pascual',
            name: 'Albergue Temporal Estadio Pascual Guerrero',
            address: 'Carrera 36 # 5-100, San Fernando, Cali, Valle del Cauca',
            city: 'Cali',
            lat: 3.4295,
            lng: -76.5435,
            type: 'shelter',
            capacity: 650,
            occupancy: 310,
            contactName: 'Alcaldía de Cali / Secretaría de Bienestar',
            contact: '(602) 898 2000',
            needs: 'Cobijas, colchonetas, pañales y agua embotellada.',
            verified: true,
            dateAdded: '11/08/2026, 13:30:00'
        },
        {
            id: 'shelter_medellin_atanasio',
            name: 'Albergue Temporal Unidad Atanasio Girardot',
            address: 'Carrera 74 # 480-10, Sector Estadio, Medellín, Antioquia',
            city: 'Medellín',
            lat: 6.2568,
            lng: -75.5902,
            type: 'shelter',
            capacity: 550,
            occupancy: 140,
            contactName: 'DAGRD Medellín',
            contact: 'Línea 123 / DAGRD',
            needs: 'Atención a familias desplazadas por afectación de edificios.',
            verified: true,
            dateAdded: '11/08/2026, 14:00:00'
        },
        {
            id: 'shelter_manizales_palogrande',
            name: 'Albergue Polideportivo Palogrande',
            address: 'Carrera 25 # 64-00, Manizales, Caldas',
            city: 'Manizales',
            lat: 5.0585,
            lng: -75.4920,
            type: 'shelter',
            capacity: 380,
            occupancy: 155,
            contactName: 'UGR Manizales / Cruz Roja',
            contact: '(606) 887 9700',
            needs: 'Cobijas térmicas, colchonetas y suero oral.',
            verified: true,
            dateAdded: '11/08/2026, 14:30:00'
        },
        {
            id: 'shelter_cartago_coliseo',
            name: 'Albergue Coliseo La Isleta',
            address: 'Calle 10 # 3-45, Cartago, Valle del Cauca',
            city: 'Cartago',
            lat: 4.7490,
            lng: -75.9130,
            type: 'shelter',
            capacity: 250,
            occupancy: 95,
            contactName: 'Gestión del Riesgo Cartago',
            contact: '311 654 3210',
            needs: 'Kits de higiene, pañales y agua embotellada.',
            verified: true,
            dateAdded: '11/08/2026, 15:00:00'
        }
    ],

    // COMEDORES DE AYUDA Y ALIMENTACIÓN COMUNITARIA
    kitchens: [
        {
            id: 'kitchen_cali_abaco',
            name: 'Comedor Comunitario Banco de Alimentos de Cali',
            address: 'Calle 24 # 6-103, Cali, Valle del Cauca',
            city: 'Cali',
            lat: 3.4560,
            lng: -76.5230,
            type: 'kitchen',
            dailyMeals: 1200,
            contactName: 'Coordinación Olla Comunitaria Cali',
            contact: '(602) 889 1234',
            needs: 'Verduras frescas, granos (fríjol, lenteja), arroz, aceite y empaques desechables para llevar.',
            schedule: '11:00 AM - 4:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 10:00:00'
        },
        {
            id: 'kitchen_medellin_saciar',
            name: 'Comedor de Emergencia Saciar Belén',
            address: 'Carrera 50 # 25-261, Barrio Belén, Medellín, Antioquia',
            city: 'Medellín',
            lat: 6.2270,
            lng: -75.5840,
            type: 'kitchen',
            dailyMeals: 800,
            contactName: 'Red de Comedores Saciar',
            contact: '(604) 444 7171',
            needs: 'Proteínas, huevos, leche, sartenes industriales y gas en cilindro.',
            schedule: '7:30 AM - 3:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 10:30:00'
        },
        {
            id: 'kitchen_manizales_pastoral',
            name: 'Comedor Comunitario Pastoral Social Manizales',
            address: 'Calle 19 # 21-34, Centro, Manizales, Caldas',
            city: 'Manizales',
            lat: 5.0665,
            lng: -75.5175,
            type: 'kitchen',
            dailyMeals: 500,
            contactName: 'Pastoral Social Arquidiócesis',
            contact: '313 765 4321',
            needs: 'Viveres de primera necesidad, panela, granos y estufas portátiles.',
            schedule: '12:00 PM - 3:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 11:00:00'
        },
        {
            id: 'kitchen_armenia_pastoral',
            name: 'Comedor de Socorro Pastoral Armenia',
            address: 'Carrera 13 # 23-15, Armenia, Quindío',
            city: 'Armenia',
            lat: 4.5380,
            lng: -75.6720,
            type: 'kitchen',
            dailyMeals: 450,
            contactName: 'Voluntariado Comedores Armenia',
            contact: '314 888 9900',
            needs: 'Platos y cubiertos compostables, agua limpia, enlatados y sal/condimentos.',
            schedule: '11:30 AM - 2:30 PM',
            verified: true,
            dateAdded: '11/08/2026, 11:15:00'
        },
        {
            id: 'kitchen_bogota_restrepo',
            name: 'Comedor Comunitario El Restrepo',
            address: 'Carrera 19 # 17-22 sur, Barrio Restrepo, Bogotá',
            city: 'Bogotá',
            lat: 4.5820,
            lng: -74.1030,
            type: 'kitchen',
            dailyMeals: 700,
            contactName: 'Secretaría de Integración Social Bogotá',
            contact: 'Línea 195',
            needs: 'Granos, aceite vegetal, azúcar, avena y frutas de larga duración.',
            schedule: '11:00 AM - 3:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 11:30:00'
        },
        {
            id: 'kitchen_quibdo_ungrd',
            name: 'Comedor de Auxilio Quibdó (Cruz Roja / UNGRD)',
            address: 'Carrera 3 # 24-12, Quibdó, Chocó',
            city: 'Quibdó',
            lat: 5.6930,
            lng: -76.6570,
            type: 'kitchen',
            dailyMeals: 1500,
            contactName: 'Brigada de Alimentación Epicentro Chocó',
            contact: '311 223 3445',
            needs: 'Agua embotellada urgente, tanques potabilizadores, arroz, atún y galletas calóricas.',
            schedule: 'Servicio Continuo 7:00 AM - 7:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 09:30:00'
        },
        {
            id: 'kitchen_abaco_nacional',
            name: 'Banco de Alimentos de Colombia (ABACO) - Red Comedores',
            address: 'Carrera 68D # 13-41, Bogotá',
            city: 'Bogotá',
            lat: 4.6410,
            lng: -74.1180,
            type: 'kitchen',
            dailyMeals: 2500,
            contactName: 'Red Nacional ABACO',
            contact: '(601) 482 4300',
            needs: 'Granos, enlatados, agua potable y kits de ración seca.',
            schedule: 'Abierto 24 Horas',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'kitchen_bucaramanga_banco',
            name: 'Banco de Alimentos de Bucaramanga',
            address: 'Calle 30 # 17-25, Bucaramanga, Santander',
            city: 'Bucaramanga',
            lat: 7.1210,
            lng: -73.1250,
            type: 'kitchen',
            dailyMeals: 900,
            contactName: 'Pastoral Social Bucaramanga',
            contact: '(607) 630 2020',
            needs: 'Alimentos no perecederos y empaques desechables.',
            schedule: '8:00 AM - 4:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 13:00:00'
        },
        {
            id: 'kitchen_pereira_pastoral',
            name: 'Comedor Solidario Diocesano Pereira',
            address: 'Carrera 7 # 23-15, Pereira, Risaralda',
            city: 'Pereira',
            lat: 4.8125,
            lng: -75.6940,
            type: 'kitchen',
            dailyMeals: 600,
            contactName: 'Diócesis de Pereira',
            contact: '(606) 335 2000',
            needs: 'Arroz, aceite, granos y estufas portátiles.',
            schedule: '11:00 AM - 3:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 14:00:00'
        },
        {
            id: 'kitchen_pasto_banco',
            name: 'Banco de Alimentos de Pasto',
            address: 'Carrera 23 # 14-30, Pasto, Nariño',
            city: 'Pasto',
            lat: 1.2110,
            lng: -77.2760,
            type: 'kitchen',
            dailyMeals: 500,
            contactName: 'Pastoral Social Nariño',
            contact: '(602) 723 5000',
            needs: 'Granos, leche en polvo y vajilla desechable.',
            schedule: '11:30 AM - 2:30 PM',
            verified: true,
            dateAdded: '11/08/2026, 15:00:00'
        }
    ],

    // ACOPIO Y ALBERGUES PARA MASCOTAS / ANIMALES
    petShelters: [
        {
            id: 'pet_bogota_idpyba',
            name: 'Punto de Acopio Pet & Unidad Vet IDPYBA / Cruz Roja',
            address: 'Avenida Caracas # 54-38, Chapinero, Bogotá',
            city: 'Bogotá',
            lat: 4.6430,
            lng: -74.0650,
            type: 'pet',
            petCapacity: 80,
            acceptedTypes: 'Perros, Gatos, Mascotas Pequeñas',
            contactName: 'Instituto de Protección Animal (IDPYBA)',
            contact: '(601) 377 7650',
            needs: 'Alimento concentrado perro/gato, guacales de transporte, gasas veterinarias, suero y cobijas.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 10:15:00'
        },
        {
            id: 'pet_cali_emergencia',
            name: 'Refugio y Acopio Animal de Emergencia Cali',
            address: 'Calle 5 # 62-00, Barrio Pampalinda, Cali, Valle del Cauca',
            city: 'Cali',
            lat: 3.4080,
            lng: -76.5480,
            type: 'pet',
            petCapacity: 120,
            acceptedTypes: 'Perros y Gatos de familias evacuadas',
            contactName: 'Bienestar Animal Cali / Red Protectora',
            contact: '316 454 3210',
            needs: 'Comida húmeda, medicamentos para quemaduras y traumatismos, collares, bozales y arena para gatos.',
            schedule: 'Abierto 24 Horas',
            verified: true,
            dateAdded: '11/08/2026, 10:45:00'
        },
        {
            id: 'pet_manizales_nubia',
            name: 'Albergue Temporal de Mascotas Manizales',
            address: 'Sector La Nubia, cerca a Aeropuerto, Manizales, Caldas',
            city: 'Manizales',
            lat: 5.0320,
            lng: -75.4650,
            type: 'pet',
            petCapacity: 60,
            acceptedTypes: 'Mascotas de evacuados y animales rescatados',
            contactName: 'Unidad de Protección Animal Manizales',
            contact: '310 987 1234',
            needs: 'Concentrado, cobijas limpias, guantes de manejo y caniles.',
            schedule: '8:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 11:20:00'
        },
        {
            id: 'pet_pereira_siempre',
            name: 'Fundación Siempre a tu Lado - Refugio Animal',
            address: 'Vía Morelia Sector Rural, Pereira, Risaralda',
            city: 'Pereira',
            lat: 4.7890,
            lng: -75.7280,
            type: 'pet',
            petCapacity: 90,
            acceptedTypes: 'Perros y Gatos rescatados del sismo',
            contactName: 'Fundación Siempre a tu Lado Pereira',
            contact: '314 765 4321',
            needs: 'Concentrado perro/gato, gasas, guacales y cobijas.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'pet_armenia_kenovy',
            name: 'Fundación Kenovy Proteccionista Animal',
            address: 'Vía Armenia-Tebaida Km 3, Armenia, Quindío',
            city: 'Armenia',
            lat: 4.5210,
            lng: -75.7020,
            type: 'pet',
            petCapacity: 75,
            acceptedTypes: 'Perros y Gatos accidentados o perdidos',
            contactName: 'Red Kenovy Armenia',
            contact: '318 654 9870',
            needs: 'Alimento concentrado, suero veterinario y antisépticos.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 13:00:00'
        },
        {
            id: 'pet_manizales_angeles',
            name: 'Fundación Ángeles de la Calle Manizales',
            address: 'Carrera 23 # 45-12, Manizales, Caldas',
            city: 'Manizales',
            lat: 5.0640,
            lng: -75.5110,
            type: 'pet',
            petCapacity: 65,
            acceptedTypes: 'Mascotas vulnerables y sin hogar',
            contactName: 'Ángeles de la Calle Manizales',
            contact: '313 543 2109',
            needs: 'Comida húmeda, guacales, cobijas y correas.',
            schedule: '8:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 14:00:00'
        },
        {
            id: 'pet_caldas_cuatropatas',
            name: 'Amigos de Cuatro Patas (Villamaría)',
            address: 'Sector Parque Principal, Villamaría, Caldas',
            city: 'Villamaría (Caldas)',
            lat: 5.0450,
            lng: -75.5140,
            type: 'pet',
            petCapacity: 50,
            acceptedTypes: 'Mascotas de familias afectadas',
            contactName: 'Protectora Villamaría',
            contact: '311 234 5678',
            needs: 'Concentrado para gatos y perros, guantes de manejo.',
            schedule: '8:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 14:30:00'
        },
        {
            id: 'pet_medellin_la_perla',
            name: 'Centro de Bienestar Animal La Perla',
            address: 'Corregimiento Altavista Sector La Perla, Medellín',
            city: 'Medellín',
            lat: 6.2210,
            lng: -75.6180,
            type: 'pet',
            petCapacity: 150,
            acceptedTypes: 'Animales de rescate en Antioquia',
            contactName: 'Secretaría de Medio Ambiente Medellín',
            contact: '(604) 385 5555',
            needs: 'Atención veterinaria urgente y alimento.',
            schedule: 'Abierto 24 Horas',
            verified: true,
            dateAdded: '11/08/2026, 15:00:00'
        },
        {
            id: 'pet_quibdo_sos',
            name: 'Rescate Animal Emergencia Chocó',
            address: 'Barrio Medrano Sector Norte, Quibdó, Chocó',
            city: 'Quibdó',
            lat: 5.6890,
            lng: -76.6540,
            type: 'pet',
            petCapacity: 40,
            acceptedTypes: 'Animales heridos o desorientados',
            contactName: 'Brigada Animalista Chocó',
            contact: '315 999 8877',
            needs: 'Alimento concentrado, agua potable y jaulas de contención.',
            schedule: 'Servicio Continuo',
            verified: true,
            dateAdded: '11/08/2026, 15:30:00'
        }
    ],

    // PUNTOS DE VOLUNTARIADO Y APOYO LOGÍSTICO
    volunteerHubs: [
        {
            id: 'vol_bogota_defensacivil',
            name: 'Sede Principal Defensa Civil Colombiana - Voluntariado',
            address: 'Carrera 13 # 19-31, Bogotá',
            city: 'Bogotá',
            lat: 4.6065,
            lng: -74.0740,
            type: 'volunteer',
            rolesNeeded: 'Armado de kits, clasificación de insumos, carga y descarga',
            contactName: 'Coordinación Nacional de Voluntarios DCC',
            contact: 'Línea 144 / (601) 327 9000',
            needs: 'Se requieren voluntarios con disposición física de 4 horas en adelante. Traer documento de identidad.',
            schedule: 'Turnos: 8:00 AM - 1:00 PM / 1:00 PM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 09:00:00'
        },
        {
            id: 'vol_cali_pmu',
            name: 'Puesto de Mando Unificado Voluntariado Cali - Plazoleta Jairo Varela',
            address: 'Av. 2 Nte. # 10-01, Granada, Cali, Valle del Cauca',
            city: 'Cali',
            lat: 3.4542,
            lng: -76.5348,
            type: 'volunteer',
            rolesNeeded: 'Logística de acopio, apoyo en comedores y registro de afectados',
            contactName: 'Gestión del Riesgo Distrital Cali',
            contact: '310 523 9811',
            needs: 'Voluntarios mayores de edad con calzado cerrado y ropa cómoda.',
            schedule: 'Convocatoria continua 24 Horas',
            verified: true,
            dateAdded: '11/08/2026, 09:30:00'
        },
        {
            id: 'vol_pereira_cruzroja',
            name: 'Voluntariado Cruz Roja Risaralda',
            address: 'Carrera 9 # 25-25, Pereira, Risaralda',
            city: 'Pereira',
            lat: 4.8110,
            lng: -75.6980,
            type: 'volunteer',
            rolesNeeded: 'Empaque de víveres, médicos/enfermeros voluntarios, apoyo psicosocial',
            contactName: 'Cruz Roja Seccional Risaralda',
            contact: '(606) 335 4880',
            needs: 'Personal de salud voluntario y brigadistas para selección de ayudas.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 10:00:00'
        },
        {
            id: 'vol_medellin_eafit',
            name: 'Puesto de Mando Voluntariado EAFIT CAS',
            address: 'Carrera 49 # 7 Sur-50, Bloque 29, Medellín, Antioquia',
            city: 'Medellín',
            lat: 6.2007,
            lng: -75.5784,
            type: 'volunteer',
            rolesNeeded: 'Selección de medicinas, empaque de insumos y logística de transporte',
            contactName: 'Voluntariado EAFIT / @CAS_OE',
            contact: '+57 322 849 1960',
            needs: 'Estudiantes y ciudadanos voluntarios con disponibilidad de tiempo.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 11:00:00'
        },
        {
            id: 'vol_quibdo_cruzroja',
            name: 'Puesto de Mando Unificado Voluntarios Chocó',
            address: 'Carrera 1 # 24-10, Frente al Malecón, Quibdó, Chocó',
            city: 'Quibdó',
            lat: 5.6945,
            lng: -76.6585,
            type: 'volunteer',
            rolesNeeded: 'Descarga de ayuda humanitaria, potabilización y distribución',
            contactName: 'Cruz Roja Chocó / Defensa Civil',
            contact: '315 888 7766',
            needs: 'Voluntarios locales con botas de caucho y guantes.',
            schedule: 'Convocatoria continua 24 Horas',
            verified: true,
            dateAdded: '11/08/2026, 12:00:00'
        },
        {
            id: 'vol_armenia_defensa',
            name: 'Sede Defensa Civil Quindío - Voluntariado',
            address: 'Carrera 19 # 35-10, Armenia, Quindío',
            city: 'Armenia',
            lat: 4.5310,
            lng: -75.6790,
            type: 'volunteer',
            rolesNeeded: 'Empaque de víveres, socorristas y brigadistas',
            contactName: 'Defensa Civil Quindío',
            contact: '(606) 745 2000',
            needs: 'Voluntarios inscritos o brigadistas con entrenamiento en auxilio.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 13:00:00'
        },
        {
            id: 'vol_manizales_cruzroja',
            name: 'Seccional Cruz Roja Caldas - Voluntariado',
            address: 'Carrera 23 # 48-40, Manizales, Caldas',
            city: 'Manizales',
            lat: 5.0630,
            lng: -75.5100,
            type: 'volunteer',
            rolesNeeded: 'Recepción de donaciones, apoyo logístico y telecomunicaciones',
            contactName: 'Cruz Roja Caldas',
            contact: '(606) 886 2000',
            needs: 'Voluntarios para organización de bodegas.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 14:00:00'
        },
        {
            id: 'vol_bucaramanga_defensa',
            name: 'Sede Defensa Civil Santander',
            address: 'Calle 36 # 23-15, Bucaramanga, Santander',
            city: 'Bucaramanga',
            lat: 7.1230,
            lng: -73.1210,
            type: 'volunteer',
            rolesNeeded: 'Organización de ayudas y apoyo a brigadas de despacho',
            contactName: 'Defensa Civil Santander',
            contact: '(607) 633 4000',
            needs: 'Personal para apoyo en carga y empaque.',
            schedule: '8:00 AM - 5:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 15:00:00'
        },
        {
            id: 'vol_pasto_cruzroja',
            name: 'Cruz Roja Seccional Nariño - Voluntariado',
            address: 'Carrera 26 # 14-25, Pasto, Nariño',
            city: 'Pasto',
            lat: 1.2130,
            lng: -77.2790,
            type: 'volunteer',
            rolesNeeded: 'Logística de despacho de ayudas y primeros auxilios',
            contactName: 'Cruz Roja Nariño',
            contact: '(602) 723 3000',
            needs: 'Voluntarios para jornadas de acopio.',
            schedule: '8:00 AM - 6:00 PM',
            verified: true,
            dateAdded: '11/08/2026, 16:00:00'
        }
    ],

    emergencyRequests: [],

    // HOSPITALES Y BANCOS DE SANGRE VERIFICADOS
    hospitals: [
        { id: 'h1', name: 'Hospital Universitario San Jorge', city: 'Pereira', department: 'Risaralda', lat: 4.8080, lng: -75.7020, status: 'overwhelmed', phone: 'Línea 123 (Urgencias Pereira)', type: 'hospital', address: 'Cra 4 # 24-88, Pereira' },
        { id: 'h2', name: 'SES Hospital de Caldas', city: 'Manizales', department: 'Caldas', lat: 5.0600, lng: -75.5100, status: 'damaged', phone: 'Línea 123 (Urgencias Manizales)', type: 'hospital', address: 'Calle 48 # 25-62, Manizales' },
        { id: 'h3', name: 'Hospital San Juan de Dios', city: 'Armenia', department: 'Quindío', lat: 4.5500, lng: -75.6600, status: 'overwhelmed', phone: 'Línea 123 (Urgencias Armenia)', type: 'hospital', address: 'Av. Bolívar # 17N-00, Armenia' },
        { id: 'h4', name: 'Hospital Universitario del Valle (HUV)', city: 'Cali', department: 'Valle del Cauca', lat: 3.4250, lng: -76.5450, status: 'overwhelmed', phone: 'Línea 123 (Urgencias Cali)', type: 'hospital', address: 'Calle 5 # 36-08, Cali' },
        { id: 'h5', name: 'Hospital San Francisco de Asís', city: 'Quibdó', department: 'Chocó', lat: 5.6950, lng: -76.6620, status: 'damaged', phone: 'Línea 123 (Urgencias Quibdó)', type: 'hospital', address: 'Carrera 1 # 26-10, Quibdó' },
        { id: 'h6', name: 'Hospital Departamental de Buenaventura', city: 'Buenaventura', department: 'Valle del Cauca', lat: 3.8830, lng: -77.0270, status: 'damaged', phone: 'Línea 123 (Urgencias Buenaventura)', type: 'hospital', address: 'Av. Simón Bolívar, Buenaventura' },
        { id: 'h_sangre_bogota', name: 'Hemocentro y Banco de Sangre Cruz Roja Bogotá', city: 'Bogotá', department: 'Cundinamarca', lat: 4.6650, lng: -74.0880, status: 'operational', phone: '(601) 437 6300 Ext 114', type: 'hospital', address: 'Carrera 68 # 68B-31, Bogotá', needs: 'Recepción urgente de donantes de sangre grupos O+, O-, A+.' },
        { id: 'h_sangre_cali', name: 'Banco de Sangre Cruz Roja Seccional Valle', city: 'Cali', department: 'Valle del Cauca', lat: 3.4270, lng: -76.5420, status: 'operational', phone: '(602) 514 1100', type: 'hospital', address: 'Calle 5 # 38-00, Cali', needs: 'Jornada continua de donación de sangre para heridos del sismo.' },
        { id: 'h_sangre_medellin', name: 'Banco de Sangre Cruz Roja Seccional Antioquia', city: 'Medellín', department: 'Antioquia', lat: 6.2280, lng: -75.5770, status: 'operational', phone: '(604) 350 5300', type: 'hospital', address: 'Carrera 52 # 25-310, Medellín', needs: 'Recepción de donantes voluntarios de sangre.' },
        { id: 'h9', name: 'Fundación Valle del Lili', city: 'Cali', department: 'Valle del Cauca', lat: 3.3740, lng: -76.5310, status: 'operational', phone: '(602) 331 9090', type: 'hospital', address: 'Av. Simón Bolívar # 98-120, Cali', needs: 'Atención priorizada de traumatología y donación de sangre.' },
        { id: 'h10', name: 'Hospital Pablo Tobón Uribe', city: 'Medellín', department: 'Antioquia', lat: 6.2770, lng: -75.5810, status: 'operational', phone: '(604) 445 9000', type: 'hospital', address: 'Calle 78B # 69-165, Medellín', needs: 'Disponibilidad para traslados médicos urgentes.' },
        { id: 'h11', name: 'Fundación Santa Fe de Bogotá', city: 'Bogotá', department: 'Cundinamarca', lat: 4.6960, lng: -74.0320, status: 'operational', phone: '(601) 603 0303', type: 'hospital', address: 'Av. 9 # 116-20, Bogotá', needs: 'Unidad de emergencias y donación de sangre habilitada.' },
        { id: 'h12', name: 'Hospital Internacional de Colombia (HIC)', city: 'Bucaramanga', department: 'Santander', lat: 7.0650, lng: -73.0880, status: 'operational', phone: '(607) 639 4040', type: 'hospital', address: 'Km 7 Autopista Floridablanca, Bucaramanga', needs: 'Banco de sangre y centro de referencia.' },
        { id: 'h13', name: 'Hospital Universitario San José de Popayán', city: 'Popayán', department: 'Cauca', lat: 2.4510, lng: -76.6010, status: 'overwhelmed', phone: '(602) 823 4508', type: 'hospital', address: 'Cra 6 # 10N-142, Popayán', needs: 'Atención urgencias y donantes de sangre O-.' },
        { id: 'h14', name: 'Hospital Departamental Universitario del Quindío', city: 'Armenia', department: 'Quindío', lat: 4.5480, lng: -75.6620, status: 'overwhelmed', phone: '(606) 749 3500', type: 'hospital', address: 'Cra 14 # 17N-00, Armenia', needs: 'Recepción continua de donantes de sangre.' },
        { id: 'h15', name: 'Banco de Sangre Cruz Roja Seccional Santander', city: 'Bucaramanga', department: 'Santander', lat: 7.1180, lng: -73.1190, status: 'operational', phone: '(607) 634 3535', type: 'hospital', address: 'Calle 45 # 28-10, Bucaramanga', needs: 'Campaña continua de donación de sangre.' },
        { id: 'h16', name: 'Hospital Universitario Hernando Moncaleano', city: 'Neiva', department: 'Huila', lat: 2.9320, lng: -75.2810, status: 'operational', phone: '(608) 871 5900', type: 'hospital', address: 'Calle 9 # 15-25, Neiva', needs: 'Recepción de emergencias y donación de sangre.' }
    ],

    donations: [
        { 
            name: 'Cruz Roja Colombiana', 
            description: 'Institución oficial humanitaria. Aportes recibidos en dinero para canalizar recursos de forma rápida en la zona afectada.', 
            website: 'https://ayuda.cruzrojacolombiana.org', 
            account: 'Cuenta Corriente Davivienda No. 0560455069996490 (Sociedad Nacional de la Cruz Roja Colombiana)', 
            type: 'national',
            officialPhone: 'WhatsApp Oficial: +57 321 213 9525 / Tel: (601) 4376300'
        },
        { 
            name: 'UNGRD - Unidad Nacional para la Gestión del Riesgo', 
            description: 'Coordinación gubernamental de respuesta del Sistema Nacional de Gestión del Riesgo.', 
            website: 'https://portal.gestiondelriesgo.gov.co/', 
            account: 'Línea Gratuita Nacional: 01-8000-113200 / PBX (+57) 601 5529696', 
            type: 'national',
            officialPhone: '01-8000-113200 / contactenos@gestiondelriesgo.gov.co'
        },
        { 
            name: 'Global Empowerment Mission (GEM)', 
            description: 'Organización internacional humanitaria respondiendo a la emergencia en Colombia. Punto físico de acopio en Doral, FL y donaciones en línea.', 
            website: 'https://www.gem.org/', 
            account: 'Donaciones en línea en gem.org | Centro físico: 1850 NW 84th Ave #100, Doral, FL 33126', 
            type: 'international',
            officialPhone: 'info@gem.org / Voluntariado: www.gem.org/volunteer'
        },
        { 
            name: 'Psicólogos Sin Fronteras', 
            description: 'Atención psicológica gratuita y confidencial para personas víctimas del terremoto en Colombia y Venezuela.', 
            website: 'https://www.instagram.com/psfvenezuela/', 
            account: 'Líneas directas: Colombia +57 316 297 1851 | Venezuela +58 412 722 5080 | EE.UU. +1 754 275 0793', 
            type: 'international',
            officialPhone: 'Colombia: +57 316 297 1851 | Venezuela: +58 412 722 5080 | USA: +1 754 275 0793'
        },
        { 
            name: 'Convoy of Hope', 
            description: 'Organización internacional humanitaria activada para respuesta al desastre sismico en Colombia.', 
            website: 'https://www.convoyofhope.org/', 
            account: 'Donaciones verificadas a través de su portal oficial', 
            type: 'international'
        },
        { 
            name: 'UNICEF Colombia', 
            description: 'Protección infantil, provisión de agua potable y kits de higiene para emergencias.', 
            website: 'https://www.unicef.org/colombia/', 
            account: 'Donación directa en su plataforma oficial en Colombia', 
            type: 'international'
        },
        { 
            name: 'International Rescue Committee (IRC)', 
            description: 'Asistencia de salud, protección y respuesta a poblaciones vulnerables.', 
            website: 'https://www.rescue.org/', 
            account: 'Donaciones en línea mediante el sitio oficial de la organización', 
            type: 'international'
        },
        { 
            name: 'ACNUR / UNHCR Colombia', 
            description: 'Suministros de emergencia y apoyo a familias en situación de vulnerabilidad o desplazamiento.', 
            website: 'https://www.acnur.org/colombia', 
            account: 'Donaciones en línea en sitio oficial institucional', 
            type: 'international'
        }
    ],

    emergencyContacts: {
        national: [
            { name: 'Línea Única de Emergencias', number: '123', icon: '🚨' },
            { name: 'Bomberos Colombia', number: '119', icon: '🚒' },
            { name: 'Cruz Roja Colombiana', number: '132', icon: '❤️' },
            { name: 'Defensa Civil Colombiana', number: '144', icon: '🛡️' },
            { name: 'Ambulancias / Urgencias Médicas', number: '125', icon: '🚑' },
            { name: 'UNGRD (Línea Nacional)', number: '01-8000-113200', icon: '📞' },
            { name: 'Psicólogos Sin Fronteras (Colombia)', number: '+57 316 297 1851', icon: '🧠' },
            { name: 'Psicólogos Sin Fronteras (Venezuela)', number: '+58 412 722 5080', icon: '🧠' },
            { name: 'Psicólogos Sin Fronteras (EE.UU.)', number: '+1 754 275 0793', icon: '🧠' }
        ],
        tips: [
            'NO ingrese a edificaciones que presenten grietas o fallas estructurales.',
            'Privilegie los mensajes de texto o chat antes que las llamadas de voz para evitar colapsar la red celular.',
            'Tenga a la mano la mochila de emergencia: agua potable, radio a pilas, linterna, botiquín e identificaciones.',
            'Siga únicamente la información de organismos oficiales (SGC, UNGRD, Cruz Roja). No difunda rumores.',
            'Ante olor a gas, cierre la llave general de inmediato y no accione interruptores de luz.',
            'Facilite el paso de vehículos de rescate y ambulancias en las vías públicas.',
            'En caso de emergencias vitales o rescate urgente, llame inmediatamente al 123.',
            'Si requiere contención emocional o ayuda psicológica gratuita, contacte a Psicólogos Sin Fronteras (+57 316 297 1851 / +58 412 722 5080 / +1 754 275 0793).'
        ]
    },

    missingPersons: []
};

// Guardar datos iniciales con la clave v6
try {
    localStorage.setItem(DATA_KEY, JSON.stringify(initialData));
} catch(e) {
    console.warn('Error inicializando datos locales:', e);
}
